apiVersion: v1
kind: Pod
metadata:
  labels:
    run: client
  name: client
  namespace: stage
spec:
  containers:
    - image: curlimages/curl
      name: client
#kubectl run curl -it --rm --image curlimages/curl -- sh
